/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Comment } from '../../models/comment';

export interface ApiPostsPostIdCommentsCommentIdDelete$Params {
  postId: number;
  commentId: number;
}

export function apiPostsPostIdCommentsCommentIdDelete(http: HttpClient, rootUrl: string, params: ApiPostsPostIdCommentsCommentIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<Comment>> {
  const rb = new RequestBuilder(rootUrl, apiPostsPostIdCommentsCommentIdDelete.PATH, 'delete');
  if (params) {
    rb.path('postId', params.postId, {});
    rb.path('commentId', params.commentId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Comment>;
    })
  );
}

apiPostsPostIdCommentsCommentIdDelete.PATH = '/api/posts/{postId}/comments/{commentId}';
