/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Comment } from '../../models/comment';
import { CommentVoteUpdate } from '../../models/comment-vote-update';

export interface ApiPostsPostIdCommentsCommentIdVotesPost$Params {
  postId: number;
  commentId: number;
      body: CommentVoteUpdate
}

export function apiPostsPostIdCommentsCommentIdVotesPost(http: HttpClient, rootUrl: string, params: ApiPostsPostIdCommentsCommentIdVotesPost$Params, context?: HttpContext): Observable<StrictHttpResponse<Comment>> {
  const rb = new RequestBuilder(rootUrl, apiPostsPostIdCommentsCommentIdVotesPost.PATH, 'post');
  if (params) {
    rb.path('postId', params.postId, {});
    rb.path('commentId', params.commentId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Comment>;
    })
  );
}

apiPostsPostIdCommentsCommentIdVotesPost.PATH = '/api/posts/{postId}/comments/{commentId}/votes';
