/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Category } from '../../models/category';
import { CategoryPut } from '../../models/category-put';

export interface ApiCategoriesCategoryIdPut$Params {
  categoryId: number;
      body: CategoryPut
}

export function apiCategoriesCategoryIdPut(http: HttpClient, rootUrl: string, params: ApiCategoriesCategoryIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<Category>> {
  const rb = new RequestBuilder(rootUrl, apiCategoriesCategoryIdPut.PATH, 'put');
  if (params) {
    rb.path('categoryId', params.categoryId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Category>;
    })
  );
}

apiCategoriesCategoryIdPut.PATH = '/api/categories/{categoryId}';
