/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Ai } from '../../models/ai';

export interface ApiAiGet$Params {

/**
 * The input text for AI content generation.
 */
  content: string;
}

export function apiAiGet(http: HttpClient, rootUrl: string, params: ApiAiGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Ai>> {
  const rb = new RequestBuilder(rootUrl, apiAiGet.PATH, 'get');
  if (params) {
    rb.query('content', params.content, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Ai>;
    })
  );
}

apiAiGet.PATH = '/api/ai';
