/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Follower } from '../../models/follower';

export interface ApiUsersUserIdFollowersGet$Params {

/**
 * ID of the user
 */
  userId: number;
}

export function apiUsersUserIdFollowersGet(http: HttpClient, rootUrl: string, params: ApiUsersUserIdFollowersGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Follower>>> {
  const rb = new RequestBuilder(rootUrl, apiUsersUserIdFollowersGet.PATH, 'get');
  if (params) {
    rb.path('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Follower>>;
    })
  );
}

apiUsersUserIdFollowersGet.PATH = '/api/users/{userId}/followers';
