/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BaseFollower } from '../../models/base-follower';
import { FollowerCreate } from '../../models/follower-create';

export interface ApiUsersUserIdFollowersPost$Params {

/**
 * ID of the user to be followed
 */
  userId: number;
      body: FollowerCreate
}

export function apiUsersUserIdFollowersPost(http: HttpClient, rootUrl: string, params: ApiUsersUserIdFollowersPost$Params, context?: HttpContext): Observable<StrictHttpResponse<BaseFollower>> {
  const rb = new RequestBuilder(rootUrl, apiUsersUserIdFollowersPost.PATH, 'post');
  if (params) {
    rb.path('userId', params.userId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BaseFollower>;
    })
  );
}

apiUsersUserIdFollowersPost.PATH = '/api/users/{userId}/followers';
