/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BaseFollower } from '../../models/base-follower';

export interface ApiUsersUserIdFollowersUnfollowIdDelete$Params {

/**
 * ID of the user
 */
  userId: number;

/**
 * ID of the follower to remove
 */
  unfollowId: number;
}

export function apiUsersUserIdFollowersUnfollowIdDelete(http: HttpClient, rootUrl: string, params: ApiUsersUserIdFollowersUnfollowIdDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<BaseFollower>> {
  const rb = new RequestBuilder(rootUrl, apiUsersUserIdFollowersUnfollowIdDelete.PATH, 'delete');
  if (params) {
    rb.path('userId', params.userId, {});
    rb.path('unfollowId', params.unfollowId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BaseFollower>;
    })
  );
}

apiUsersUserIdFollowersUnfollowIdDelete.PATH = '/api/users/{userId}/followers/{unfollowId}';
