/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { Ai } from '../models/ai';
import { apiAiGet } from '../fn/ai/api-ai-get';
import { ApiAiGet$Params } from '../fn/ai/api-ai-get';

@Injectable({ providedIn: 'root' })
export class AiService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiAiGet()` */
  static readonly ApiAiGetPath = '/api/ai';

  /**
   * Generate AI content for a blog post.
   *
   * Generates AI-generated content for a blog post based on provided input.
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAiGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAiGet$Response(params: ApiAiGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Ai>> {
    return apiAiGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Generate AI content for a blog post.
   *
   * Generates AI-generated content for a blog post based on provided input.
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAiGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAiGet(params: ApiAiGet$Params, context?: HttpContext): Observable<Ai> {
    return this.apiAiGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<Ai>): Ai => r.body)
    );
  }

}
