/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiAuthLoginPost } from '../fn/auth/api-auth-login-post';
import { ApiAuthLoginPost$Params } from '../fn/auth/api-auth-login-post';
import { apiAuthProfileGet } from '../fn/auth/api-auth-profile-get';
import { ApiAuthProfileGet$Params } from '../fn/auth/api-auth-profile-get';
import { apiAuthRegisterPost } from '../fn/auth/api-auth-register-post';
import { ApiAuthRegisterPost$Params } from '../fn/auth/api-auth-register-post';
import { User } from '../models/user';
import { UserLoginRes } from '../models/user-login-res';
import { UserRegisterRes } from '../models/user-register-res';

@Injectable({ providedIn: 'root' })
export class AuthService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiAuthRegisterPost()` */
  static readonly ApiAuthRegisterPostPath = '/api/auth/register';

  /**
   * Register a new user.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAuthRegisterPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  apiAuthRegisterPost$Response(params: ApiAuthRegisterPost$Params, context?: HttpContext): Observable<StrictHttpResponse<UserRegisterRes>> {
    return apiAuthRegisterPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Register a new user.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAuthRegisterPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  apiAuthRegisterPost(params: ApiAuthRegisterPost$Params, context?: HttpContext): Observable<UserRegisterRes> {
    return this.apiAuthRegisterPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserRegisterRes>): UserRegisterRes => r.body)
    );
  }

  /** Path part for operation `apiAuthLoginPost()` */
  static readonly ApiAuthLoginPostPath = '/api/auth/login';

  /**
   * Login a user.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAuthLoginPost()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  apiAuthLoginPost$Response(params: ApiAuthLoginPost$Params, context?: HttpContext): Observable<StrictHttpResponse<UserLoginRes>> {
    return apiAuthLoginPost(this.http, this.rootUrl, params, context);
  }

  /**
   * Login a user.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAuthLoginPost$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  apiAuthLoginPost(params: ApiAuthLoginPost$Params, context?: HttpContext): Observable<UserLoginRes> {
    return this.apiAuthLoginPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserLoginRes>): UserLoginRes => r.body)
    );
  }

  /** Path part for operation `apiAuthProfileGet()` */
  static readonly ApiAuthProfileGetPath = '/api/auth/profile';

  /**
   * Get the current user's profile.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAuthProfileGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAuthProfileGet$Response(params?: ApiAuthProfileGet$Params, context?: HttpContext): Observable<StrictHttpResponse<User>> {
    return apiAuthProfileGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Get the current user's profile.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAuthProfileGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAuthProfileGet(params?: ApiAuthProfileGet$Params, context?: HttpContext): Observable<User> {
    return this.apiAuthProfileGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<User>): User => r.body)
    );
  }

}
