/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Post } from '../../models/post';

export interface ApiPostsGet$Params {

/**
 * Filter posts by user ID
 */
  userId?: number;

/**
 * Filter posts by published status
 */
  published?: boolean;
}

export function apiPostsGet(http: HttpClient, rootUrl: string, params?: ApiPostsGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Post>>> {
  const rb = new RequestBuilder(rootUrl, apiPostsGet.PATH, 'get');
  if (params) {
    rb.query('userId', params.userId, {});
    rb.query('published', params.published, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Post>>;
    })
  );
}

apiPostsGet.PATH = '/api/posts';
