/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PostVote } from '../../models/post-vote';

export interface ApiPostsPostIdVotesGet$Params {

/**
 * ID of the post
 */
  postId: number;

/**
 * Filter by vote type (LIKE or DISLIKE)
 */
  type?: 'LIKE' | 'DISLIKE';
}

export function apiPostsPostIdVotesGet(http: HttpClient, rootUrl: string, params: ApiPostsPostIdVotesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PostVote>>> {
  const rb = new RequestBuilder(rootUrl, apiPostsPostIdVotesGet.PATH, 'get');
  if (params) {
    rb.path('postId', params.postId, {});
    rb.query('type', params.type, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PostVote>>;
    })
  );
}

apiPostsPostIdVotesGet.PATH = '/api/posts/{postId}/votes';
