/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Post } from '../../models/post';
import { PostPut } from '../../models/post-put';

export interface ApiPostsPostIdPut$Params {
  postId: number;
      body: PostPut
}

export function apiPostsPostIdPut(http: HttpClient, rootUrl: string, params: ApiPostsPostIdPut$Params, context?: HttpContext): Observable<StrictHttpResponse<Post>> {
  const rb = new RequestBuilder(rootUrl, apiPostsPostIdPut.PATH, 'put');
  if (params) {
    rb.path('postId', params.postId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Post>;
    })
  );
}

apiPostsPostIdPut.PATH = '/api/posts/{postId}';
