/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Post {
  author: {
'id': number;
'username': string;
'email': string;
};
  categories: Array<{
'id': number;
'name': string;
'description'?: string;
}>;
  content: string;
  createdAt: string;
  id: number;
  published?: boolean;
  tags: Array<{
'id': number;
'name': string;
'description'?: string;
}>;
  title: string;
  updatedAt: string;
  votesCount?: number;
}
