/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Post {
  author: {
'id': number;
'username': string;
'email': string;
};
  content: string;
  createdAt: string;
  id: number;
  published?: boolean;
  title: string;
  updatedAt: string;
}
