/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PostPut {
  authorId?: number;
  categories?: Array<number>;
  content?: string;
  published?: boolean;
  tags?: Array<number>;
  title?: string;
}
