/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PostVote {
  createdAt: string;
  id: number;
  postId: number;
  updatedAt: string;
  userId: number;
  value: 'LIKE' | 'DISLIKE';
}
