/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PostPost {
  authorId: number;
  content: string;
  published?: boolean;
  title: string;
}
