/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Tag {
  createdAt: string;
  description?: string;
  id: number;
  name: string;
  updatedAt: string;
}
