/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserRegisterRes {
  token: string;
  user: {
'id': number;
'username': string;
'email': string;
'createdAt': string;
'updatedAt': string;
'followersCount'?: number;
'followingCount'?: number;
};
}
