/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface User {
  createdAt: string;
  email: string;
  id: number;
  password: string;
  updatedAt: string;
  username: string;
}
