/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Ai } from './models/ai';
export type { BaseFollower } from './models/base-follower';
export type { Category } from './models/category';
export type { CategoryPost } from './models/category-post';
export type { CategoryPut } from './models/category-put';
export type { Comment } from './models/comment';
export type { CommentPost } from './models/comment-post';
export type { CommentPut } from './models/comment-put';
export type { Follower } from './models/follower';
export type { FollowerCreate } from './models/follower-create';
export type { Login } from './models/login';
export type { Post } from './models/post';
export type { PostPost } from './models/post-post';
export type { PostPut } from './models/post-put';
export type { Tag } from './models/tag';
export type { TagPost } from './models/tag-post';
export type { TagPut } from './models/tag-put';
export type { User } from './models/user';
export type { UserLoginRes } from './models/user-login-res';
export type { UserPost } from './models/user-post';
export type { UserPut } from './models/user-put';
export type { UserRegisterRes } from './models/user-register-res';
